// Auto-generated by AudioManagerWindow
public static class AudioNames
{
    public const string BGM_BACKGROUND = "BGM_Background";
    public const string SFX_BUTTON_CANCEL_CLICK = "SFX_ButtonCancelClick";
    public const string SFX_BUTTON_CLICK = "SFX_ButtonClick";
    public const string SFX_FAILED = "SFX_Failed";
    public const string SFX_REVEAL_FAILURE = "SFX_RevealFailure";
    public const string SFX_REVEAL_SUCCESS = "SFX_RevealSuccess";
    public const string SFX_WINNING = "SFX_Winning";
}
